### ISSUE TITLE
App no longer available in play store

### ISSUE THREAD

**Issue by DreierF** [dkhmelenko/Varis-Android#29]
Hi Dmytro,

did you remove the app from the play store?
https://play.google.com/store/apps/details?id=com.khmelenko.lab.travisclient

Cheers,
Florian

**Comment by dkhmelenko** [comment]
The app was removed today by Google since yesterday update. The reason is that it uses the icon and the name of Travis brand.
There are two possible solutions: 
1. contact Travis team and get confirmation from them that the app is allowed to use their brand. Then notify Google in case of success and the app should become available again.
2. Change application package, name and icon and submit it to play store as a new app.

I will try to contact Travis team as soon as possible. In case of rejection from their side, changing application name is only the option.

Sorry that it happend so, for me it's also unexpected thing today.

If you have any other suggestions, I'm open for them.

**Comment by dkhmelenko** [comment]
This is an email from Google
```After review, Travis Client, com.khmelenko.lab.travisclient, has been suspended and removed from Google Play as a policy strike because it violates the impersonation policy.

Next Steps

Read through the Impersonation article for more details and examples of policy violations.
Make sure your app is compliant with the Impersonation and Intellectual Property policy and all other policies listed in the Developer Program Policies. Remember additional enforcement could occur if there are further policy issues with your apps.
Sign in to your Developer Console and submit the policy compliant app using a new package name and a new app name.```

**Comment by dkhmelenko** [comment]
The response from Travis Team
```
Hi Dmytro,

Thank you for writing in about this and for creating the Android client :) 

In regards to what you can and cannot do with our logo/branding we have a few rules that can be found here: https://travis-ci.com/logo.

For legal reasons and choosing between the options Google suggested you, the one that fits this rules is (1): 

> Rename the app and use different application icon.

Using our brand name "Travis CI" and using or altering our logo in any way cannot be done. 

However, if you're thinking about visually hinting with Travis CI mascot themes like the red mustache, construction hat or goggles is permitted provided you do not directly abstract any point of our logo's vector shapes. 
Also, we'd request that you have some copy in the application that you are not affiliated with travis-ci.com.
```

**Comment by dkhmelenko** [comment]
@DreierF New app with latest changes is available. 
https://play.google.com/store/apps/details?id=com.khmelenko.lab.varis
