### ISSUE TITLE
Support GitHub Token API

### ISSUE THREAD

**Issue by uilianries** [dkhmelenko/Varis-Android#47]
Hi!

Your project is the best app to monitor Travis CI. Thanks for providing this amazing tool for the community!

Publish username and password could not be safe.

Github provides API key to access all levels. It's safer and can be revoked when needed. 

Consider providing an option to API token instead of password.

Regards!

**Comment by nikhilbansal97** [comment]
Hi @uilianries I would like to work on this issue!

**Comment by uilianries** [comment]
Really appreciate!

**Comment by nikhilbansal97** [comment]
@uilianries Logging in using the API token would require OAuth. Is this registered for OAuth and do we have any `client_key` and `client_secret`?

**Comment by nikhilbansal97** [comment]
@uilianries To use Oauth Token, `client_id` and `client_secret` must be needed that is unique for the app. How do I get it?

**Comment by dkhmelenko** [comment]
Here is a documentation of the auth on Travis CI. https://docs.travis-ci.com/api#authentication

So in order to authenticate on Travis CI, you need to provide a token. And a token can be received through the GitHub. 

Yes, we can implement one more option for users to provide a token instead of credentials. But how convenient will it be to input a token comparing to credentials? Most of the users know their GitHub credentials and don't care about creating a token.

I'm open for suggestions and ideas :)
